.htaccess, index.php, style/base.css, style/color.css, style/style.css, tpl/body_tpl.php
add: index 페이지
- index.php : 메인 페이지 (로그인, 비로그인)
- htaccess : php 확장자 제거
- tpl : 페이지 노출
- style css : 페이지 관리하는 css
- color css : 색상 관리하는 css
- base css : 중복으로 많이 사용하는 css
=> add: index 페이지

tpl/body_tpl.php
ISSUE #3 
모바일 환경에서 input 필드 클릭해도 확대되지 않도록 수정함
=> [FIX #3] input 필드 확대 되지 않도록 수정

admin_view/index.php, index.php, style/admin.css, style/base.css, tpl/body_tpl.php, view/signup.php, view_control/login_control.php
=> update: 로그인 시 유저 롤 추가

admin_control/add_match_player.php, admin_control/minus_match_player.php, model/JwtApiCall.php, model/RestApiCall.php, style/admin.css, style/style.css, view/match.php, view_control/attendance_check.php
20230823 PR
- add
- 출석확인 기능 추가
- update
- 오타 및 공백 삭제
- api 예외처리 수정
- 출석확인 기능 추가에 따른 css 수정
=> 20230823 PR

admin_control/match_update.php, admin_view/match_detail.php
=> add : 경기 제목 수정

admin_control/match_create.php, admin_control/match_delete.php, admin_control/match_update.php, admin_data/match_data.php, admin_view/match_detail.php, style/admin.css, style/base.css, style/style.css
수정사항
- 코드 정렬 수정
- 경기 정보 불러오는 파일 생성
- 팝업 기본 값 수정
추가 사항 
- 경기 수정 기능 추가(수정 팝업 추가)
- 경기 삭제 기능 추가
=> 20230827 PR

admin_data/match_member_data.php, admin_view/match_detail.php
update 
- 관리자 경기 상세 정보 fetch type을 lazy 방식으로 수정
=> 230829 관리자 경기 상세 정보 fetch type을 lazy 방식으로 수정

admin_control/expenses_match_player.php, admin_data/match_member_data.php, admin_view/index.php, admin_view/match_detail.php, index.php, style/admin.css, view/match.php, view_control/purchasereq_check.php
update
- 만들지 않은 기능 접근 못하도록 수정
add
- 사용자 납부 확인 기능 추가
- 관리자 납부 확인 기능 추가
=> 2023-08-30 PR

admin_data/match_member_data.php, style/admin.css, style/base.css, style/style.css, view/signup.php
update
- 경기수정 ui 수정 (텍스트들이 팝업 밖으로 노출 되는 현상)
- 회원가입 유효성 체크(영문,숫자,_,!,@만 가능하도록)
- select 박스, 날짜 input 태그 길이, 높이 값 수정 (재현 안되어 수정 확인 불가)
- 모바일 환경에서 경기 정보(관리자) 버튼 글자 내려가는거 수정
- 관리자 로그인 후 세션만료 시 다시 로그인 프로세스로 이동하도록 수정
- 화면 크기가 작을 때 헤더 폰트 사이즈 수정
- 화면 작을 때 팝업 좌우 공백 추가
추가 수정 필요
- 납부 확인 클릭 시 페이지 새로고침이 되나 명단 수정이 안됨 (재현 안됨)
- 리얼서버 스테이지서버 구분 (이해 못함)
=> 2023-08-31 PR

style/base.css, view_control/signup_control.php
update
- 회원가입 서버 연결 위치 조정
- 이전에는 유효성 검사 한 이유가 없었다....
=> update: 회원가입 서버 연결 위치 조정

admin_control/add_match_player.php, admin_control/expenses_match_player.php, admin_control/match_create.php, admin_control/match_delete.php, admin_control/match_update.php, admin_control/minus_match_player.php, admin_data/match_data.php, admin_data/match_member_data.php, admin_view/index.php, admin_view/match.php, admin_view/match_create.php, admin_view/member.php, config/config.php, index.php, tpl/body_tpl.php, view/match.php, view_control/attendance_check.php, view_control/login_control.php, view_control/purchasereq_check.php, view_control/signup_control.php
add
- config.php를 통해 api 주소 전역으로 사용
update
- 기존 api주소 전역 변수로 변경
- 관리자 페이지 접속 시 로그인 한 유저 체크 조건 수정
=> add : config.php를 통해 api 주소 전역으로 사용 / update: 기존 api주소 전역 변수로 변경

config/config.php, style/admin.css
update
- api 주소 조건 변경
- 납부 확인 버튼 거리 조정
=> update: api 주소 조건 변경 및 납부 확인 버튼 거리 조정

tpl/body_tpl.php
=> Feat: 네이버 지도 api 연결 스크립트 추가

admin_data/match_member_data.php, style/admin.css, view/match.php
[Fix]
- 납부 확인 요청 버튼 안겹치도록 수정
[Feat]
- 인원 조회 시 가나다 순으로 정렬 후 노출
- 출석체크 시 위치 권한이 없는 등 정보를 가져오지 못하는 경우 분기 추가
=> Fix: 버튼 안겹치도록 수정 / Feat: 이름 정렬 및 위치 권한 분기

admin_control/add_match_player.php, admin_control/expenses_match_player.php, admin_control/match_create.php, admin_control/match_delete.php, admin_control/match_update.php, admin_control/minus_match_player.php, loading/loading.php, view/match.php, view_control/login_control.php, view_control/purchasereq_check.php
Feat
- 로딩 표시하는 페이지 추가
- api 요청 후 팝업 전까지 로딩 표시 추가
Refactor
- 납부 확인 코드는 통일성을 위해 ajax로 리팩토링
=> Feat : api 요청 후 팝업 전까지 로딩 표시 추가

admin_data/match_member_data.php, admin_view/match_create.php, admin_view/match_detail.php, style/admin.css, style/color.css
feat
- 출석 및 납부 현황에 따라 텍스트 색 추가
- 경기위치 중대부고/잠실 로꼬스타디움/용산 은 선택할 수 있는 버튼 추가
fix
- 납부 확인 버튼 안겹치도록 수정
=> feat: 출석 및 납부 현황에 따라 텍스트 색 추가 / fix: 납부 확인 버튼 안겹치도록 수정

index.php, style/style.css, view_control/login_control.php, view_control/signup_control.php
feat
- 로그인 정보 쿠키에 저장
- 회원가입시 비밀번호 정규식 추가
=> feat : 로그인 정보 쿠키에 저장 / 회원가입시 비밀번호 정규식 추가

view/match.php
Feat
- 출석 현황 및 납부 현황에 따른 버튼 UI 변경
Fix 
- 정확한 위치 정보 옵션 추가
- 기대효과 -> 출석 에러 확률 줄어듬
=> Feat: 출석 현황 및 납부 현황에 따른 버튼 UI 변경 / Fix : 정확한 위치 정보 옵션 추가

admin_management/index.php, admin_management/member_detail.php, admin_view/index.php, admin_view/member.php
FEAT: 
- 부원 관리 페이지 
- 개별 관리 페이지
=> FEAT: 부원 관리 페이지 및 개별 관리 페이지 추가

admin_control/attend_process.php, admin_management/member_detail.php
=> FEAT: 부원 경기 직권 출석 기능 추가

admin_data/joinend_game_detail.php
=> FEAT: 직권 처리 데이터 및 팝업 연결 추가

style/admin.css
=> FEAT: 직권 출석 처리 팝업 css 추가

admin_management/member_detail.php, style/admin.css, tpl/body_tpl.php
=> FEAT: 경기 참여율 그래프화

admin_management/member_detail.php
=> Fix: 전체 경기 참여율 안맞던 현상 수정

admin_management/member_detail.php
Fix
- total, joined 경기가 0일경우 경기 참여율 100%로 되는 분기 조건 수정
=> Fix: total, joined 경기가 0일경우 경기 참여율 100%로 되는 분기 조건 수정

tpl/body_tpl.php
=> add : 제니퍼 프론트 툴 도입

admin_data/joinend_game_detail.php, admin_management/index.php, admin_management/member_detail.php, admin_view/index.php, admin_view/member.php, style/admin.css, style/base.css, tpl/body_tpl.php
=> Style: 관리자메뉴 디자인 수정

admin_management/index.php, admin_view/index.php, admin_view/member.php, index.php, view/match.php, view/my_info.php
=> FEAT: 마이페이지 생성

admin_management/index.php, admin_management/member_detail.php, admin_view/index.php, admin_view/match.php, admin_view/match_create.php, admin_view/match_detail.php, admin_view/member.php, config/config.php, index.php, maintenance.php, style/admin.css, view/match.php, view/my_info.php, view/signup.php
=> style: 경기 관리 부분 스타일 통일

tpl/body_tpl.php
Fix: 점검 중일 때 config 파일 에러나는 현상 수정
=> Fix: 점검 중일 때 config 파일 에러나는 현상 수정

admin_view/match_create.php
=> FIX: 경기 중복 생성 버그 수정

manifest.json
=> FEAT: PWA manifest 파일 추가
